### ISSUE TITLE
CSRF tokens

### ISSUE THREAD

**Issue by hannesm** [robur-coop/mollymawk#40]
we need them for all the forms. emit them and check them on receiving form data.

**Comment by PizieDust** [comment]
@hannesm So from my understanding, `csrf` tokens are to prevent `cross-site` attacks and we can implement a new middleware that we attach to all post request, basically any request which changes state.
We can go for it one of two ways:
- When a user request for a page that has a form, we generate a token and embed it on the form, and ship the token as a cookie on the users session. When the user submits the form, we read the token from that form and compare it to the cookie we shipped to them. However, if the attacker can somehow access the cookies of the user (maybe in some edge cases), it can weaken this method.
OR
- When the user request for the page, we generate the token and embed it on the form, and save the same session of the user including the token on our server. When the user has submitted the form, we compare that token from the form, to the copy we have on the server. and then validate the token match or if there's a mismatch we stop processing the request.

Do you have a preference between the two implementations?

**Comment by hannesm** [comment]
My preference is the second, and I think we don't need to store that token persistently (on disk) -- but just have it around somewhere. :) Thanks for your investigation.

**Comment by PizieDust** [comment]
> My preference is the second, and I think we don't need to store that token persistently (on disk) -- but just have it around somewhere. :) Thanks for your investigation.

Me too. and yes, we don't have to keep it persistently. In fact the faster the token changes and the more random it is, the better.
