### ISSUE TITLE
Feature: can we have the tables displayed being sortable by each column (maybe with some javascript)

### ISSUE THREAD

**Issue by hannesm** [robur-coop/mollymawk#75]
That'd make it easy to view the unikernels by name, but also by cpuid, or assigned memory etc. I'm sure there's some javascript package around that enables sorting ;)

**Comment by PizieDust** [comment]
Currently there's a search box above the table that filters based on what you type in it. 
but I can quickly drum up some functionality to allow us to sort the data

**Comment by hannesm** [comment]
Thanks @PizieDust. The search is nice, but only filters by name. I'd be keen to find an answer to "which unikernels are running on CPU 10?"
