### ISSUE TITLE
Volumes UI: "View" is unclear

### ISSUE THREAD

**Issue by hannesm** [robur-coop/mollymawk#92]
The volumes UI looks amazing. But I initially was confused by the `View` button -- since I expected to get the data of the volume -- but instead I was redirected to the unikernel that is using the block device.

Since the "get" and "set" operations are to be implemented (see #32), we should find some good names for the buttons :)

I also like the pie chart a lot. Thanks so much @PizieDust :)

**Comment by PizieDust** [comment]
Yes that's right. "View" is not very explanatory. 
I was thinking of a way to display the data. For instance if we read data from a block device, do we just display this as text? What is the data corresponds to images?

Also, the way I understand the "get" operation, we have to give it an offset so it reads to that offset?

**Comment by hannesm** [comment]
> Yes that's right. "View" is not very explanatory. I was thinking of a way to display the data. For instance if we read data from a block device, do we just display this as text? What is the data corresponds to images?

I'd have a "download" button, and allow the data to be downloaded as application/octet-stream.

> Also, the way I understand the "get" operation, we have to give it an offset so it reads to that offset?

The `int` provided to `` `Block_dump `` is the compression level to use. 0 for none, 9 for highest (I guess). It uses https://github.com/mirage/decompress.

**Comment by PizieDust** [comment]
Oh I see. Thank you. I think I understand it now.

**Comment by hannesm** [comment]
#95 addresses this
